name: test
env:
  CI: true
on:
  push:
    branches:
      - master
    tags:
      - "!*"
jobs:
  release:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      - name: setup-java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: install
        run: npm install && mvn install
      - name: version
        run: npm -v && java -version